/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as RenderRouteImport } from './routes/render'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ControllerRouteImport } from './routes/controller'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ControllerSessionIdRouteImport } from './routes/controller/$sessionId'
import { Route as DashboardRundownsIndexRouteImport } from './routes/dashboard/rundowns/index'
import { Route as DashboardDatasourcesIndexRouteImport } from './routes/dashboard/datasources/index'
import { Route as DashboardCuesheetsIndexRouteImport } from './routes/dashboard/cuesheets/index'
import { Route as DashboardCharactersIndexRouteImport } from './routes/dashboard/characters/index'
import { Route as DashboardBroadcastIndexRouteImport } from './routes/dashboard/broadcast/index'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard/admin/index'
import { Route as DashboardRundownsRundownIdRouteImport } from './routes/dashboard/rundowns/$rundownId'
import { Route as DashboardCuesheetsCuesheetIdRouteImport } from './routes/dashboard/cuesheets/$cuesheetId'
import { Route as DashboardStudioOverlaysIndexRouteImport } from './routes/dashboard/studio/overlays/index'
import { Route as DashboardStudioGraphicsIndexRouteImport } from './routes/dashboard/studio/graphics/index'
import { Route as DashboardStudioBundlesIndexRouteImport } from './routes/dashboard/studio/bundles/index'
import { Route as DashboardAssetsImagesIndexRouteImport } from './routes/dashboard/assets/images/index'
import { Route as DashboardAssetsFontsIndexRouteImport } from './routes/dashboard/assets/fonts/index'
import { Route as DashboardStudioWhiteboardsWhiteboardIdRouteImport } from './routes/dashboard/studio/whiteboards/$whiteboardId'
import { Route as DashboardStudioGraphicsGraphicIdRouteImport } from './routes/dashboard/studio/graphics/$graphicId'
import { Route as DashboardStudioBundlesBundleIdRouteImport } from './routes/dashboard/studio/bundles/$bundleId'
import { Route as DashboardStudioOverlaysEditorPluginIdRouteImport } from './routes/dashboard/studio/overlays/editor.$pluginId'
import { Route as DashboardStudioGraphicsGridTemplatesNewRouteImport } from './routes/dashboard/studio/graphics/grid-templates/new'
import { Route as DashboardStudioGraphicsGridTemplatesTemplateIdRouteImport } from './routes/dashboard/studio/graphics/grid-templates/$templateId'

const DashboardGraphicTaggingLazyRouteImport = createFileRoute(
  '/dashboard/graphic-tagging',
)()
const DashboardAiCuesheetLazyRouteImport = createFileRoute(
  '/dashboard/ai-cuesheet',
)()
const DashboardStudioWhiteboardsIndexLazyRouteImport = createFileRoute(
  '/dashboard/studio/whiteboards/',
)()
const DashboardStudioGridTemplatesIndexLazyRouteImport = createFileRoute(
  '/dashboard/studio/grid-templates/',
)()

const RenderRoute = RenderRouteImport.update({
  id: '/render',
  path: '/render',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ControllerRoute = ControllerRouteImport.update({
  id: '/controller',
  path: '/controller',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/index.lazy').then((d) => d.Route),
)
const DashboardGraphicTaggingLazyRoute =
  DashboardGraphicTaggingLazyRouteImport.update({
    id: '/graphic-tagging',
    path: '/graphic-tagging',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/graphic-tagging.lazy').then((d) => d.Route),
  )
const DashboardAiCuesheetLazyRoute = DashboardAiCuesheetLazyRouteImport.update({
  id: '/ai-cuesheet',
  path: '/ai-cuesheet',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/ai-cuesheet.lazy').then((d) => d.Route),
)
const ControllerSessionIdRoute = ControllerSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => ControllerRoute,
} as any).lazy(() =>
  import('./routes/controller/$sessionId.lazy').then((d) => d.Route),
)
const DashboardRundownsIndexRoute = DashboardRundownsIndexRouteImport.update({
  id: '/rundowns/',
  path: '/rundowns/',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/rundowns/index.lazy').then((d) => d.Route),
)
const DashboardDatasourcesIndexRoute =
  DashboardDatasourcesIndexRouteImport.update({
    id: '/datasources/',
    path: '/datasources/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/datasources/index.lazy').then((d) => d.Route),
  )
const DashboardCuesheetsIndexRoute = DashboardCuesheetsIndexRouteImport.update({
  id: '/cuesheets/',
  path: '/cuesheets/',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/cuesheets/index.lazy').then((d) => d.Route),
)
const DashboardCharactersIndexRoute =
  DashboardCharactersIndexRouteImport.update({
    id: '/characters/',
    path: '/characters/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardBroadcastIndexRoute = DashboardBroadcastIndexRouteImport.update({
  id: '/broadcast/',
  path: '/broadcast/',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/broadcast/index.lazy').then((d) => d.Route),
)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/admin/index.lazy').then((d) => d.Route),
)
const DashboardRundownsRundownIdRoute =
  DashboardRundownsRundownIdRouteImport.update({
    id: '/rundowns/$rundownId',
    path: '/rundowns/$rundownId',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/rundowns/$rundownId.lazy').then((d) => d.Route),
  )
const DashboardCuesheetsCuesheetIdRoute =
  DashboardCuesheetsCuesheetIdRouteImport.update({
    id: '/cuesheets/$cuesheetId',
    path: '/cuesheets/$cuesheetId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardStudioWhiteboardsIndexLazyRoute =
  DashboardStudioWhiteboardsIndexLazyRouteImport.update({
    id: '/studio/whiteboards/',
    path: '/studio/whiteboards/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/studio/whiteboards/index.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardStudioGridTemplatesIndexLazyRoute =
  DashboardStudioGridTemplatesIndexLazyRouteImport.update({
    id: '/studio/grid-templates/',
    path: '/studio/grid-templates/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/studio/grid-templates/index.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardStudioOverlaysIndexRoute =
  DashboardStudioOverlaysIndexRouteImport.update({
    id: '/studio/overlays/',
    path: '/studio/overlays/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/studio/overlays/index.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardStudioGraphicsIndexRoute =
  DashboardStudioGraphicsIndexRouteImport.update({
    id: '/studio/graphics/',
    path: '/studio/graphics/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/studio/graphics/index.lazy').then(
      (d) => d.Route,
    ),
  )
const DashboardStudioBundlesIndexRoute =
  DashboardStudioBundlesIndexRouteImport.update({
    id: '/studio/bundles/',
    path: '/studio/bundles/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAssetsImagesIndexRoute =
  DashboardAssetsImagesIndexRouteImport.update({
    id: '/assets/images/',
    path: '/assets/images/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/assets/images/index.lazy').then((d) => d.Route),
  )
const DashboardAssetsFontsIndexRoute =
  DashboardAssetsFontsIndexRouteImport.update({
    id: '/assets/fonts/',
    path: '/assets/fonts/',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/assets/fonts/index.lazy').then((d) => d.Route),
  )
const DashboardStudioWhiteboardsWhiteboardIdRoute =
  DashboardStudioWhiteboardsWhiteboardIdRouteImport.update({
    id: '/studio/whiteboards/$whiteboardId',
    path: '/studio/whiteboards/$whiteboardId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardStudioGraphicsGraphicIdRoute =
  DashboardStudioGraphicsGraphicIdRouteImport.update({
    id: '/studio/graphics/$graphicId',
    path: '/studio/graphics/$graphicId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardStudioBundlesBundleIdRoute =
  DashboardStudioBundlesBundleIdRouteImport.update({
    id: '/studio/bundles/$bundleId',
    path: '/studio/bundles/$bundleId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardStudioOverlaysEditorPluginIdRoute =
  DashboardStudioOverlaysEditorPluginIdRouteImport.update({
    id: '/studio/overlays/editor/$pluginId',
    path: '/studio/overlays/editor/$pluginId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardStudioGraphicsGridTemplatesNewRoute =
  DashboardStudioGraphicsGridTemplatesNewRouteImport.update({
    id: '/studio/graphics/grid-templates/new',
    path: '/studio/graphics/grid-templates/new',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardStudioGraphicsGridTemplatesTemplateIdRoute =
  DashboardStudioGraphicsGridTemplatesTemplateIdRouteImport.update({
    id: '/studio/graphics/grid-templates/$templateId',
    path: '/studio/graphics/grid-templates/$templateId',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/controller': typeof ControllerRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/render': typeof RenderRoute
  '/controller/$sessionId': typeof ControllerSessionIdRoute
  '/dashboard/ai-cuesheet': typeof DashboardAiCuesheetLazyRoute
  '/dashboard/graphic-tagging': typeof DashboardGraphicTaggingLazyRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/cuesheets/$cuesheetId': typeof DashboardCuesheetsCuesheetIdRoute
  '/dashboard/rundowns/$rundownId': typeof DashboardRundownsRundownIdRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/broadcast/': typeof DashboardBroadcastIndexRoute
  '/dashboard/characters/': typeof DashboardCharactersIndexRoute
  '/dashboard/cuesheets/': typeof DashboardCuesheetsIndexRoute
  '/dashboard/datasources/': typeof DashboardDatasourcesIndexRoute
  '/dashboard/rundowns/': typeof DashboardRundownsIndexRoute
  '/dashboard/studio/bundles/$bundleId': typeof DashboardStudioBundlesBundleIdRoute
  '/dashboard/studio/graphics/$graphicId': typeof DashboardStudioGraphicsGraphicIdRoute
  '/dashboard/studio/whiteboards/$whiteboardId': typeof DashboardStudioWhiteboardsWhiteboardIdRoute
  '/dashboard/assets/fonts/': typeof DashboardAssetsFontsIndexRoute
  '/dashboard/assets/images/': typeof DashboardAssetsImagesIndexRoute
  '/dashboard/studio/bundles/': typeof DashboardStudioBundlesIndexRoute
  '/dashboard/studio/graphics/': typeof DashboardStudioGraphicsIndexRoute
  '/dashboard/studio/overlays/': typeof DashboardStudioOverlaysIndexRoute
  '/dashboard/studio/grid-templates/': typeof DashboardStudioGridTemplatesIndexLazyRoute
  '/dashboard/studio/whiteboards/': typeof DashboardStudioWhiteboardsIndexLazyRoute
  '/dashboard/studio/graphics/grid-templates/$templateId': typeof DashboardStudioGraphicsGridTemplatesTemplateIdRoute
  '/dashboard/studio/graphics/grid-templates/new': typeof DashboardStudioGraphicsGridTemplatesNewRoute
  '/dashboard/studio/overlays/editor/$pluginId': typeof DashboardStudioOverlaysEditorPluginIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/controller': typeof ControllerRouteWithChildren
  '/login': typeof LoginRoute
  '/render': typeof RenderRoute
  '/controller/$sessionId': typeof ControllerSessionIdRoute
  '/dashboard/ai-cuesheet': typeof DashboardAiCuesheetLazyRoute
  '/dashboard/graphic-tagging': typeof DashboardGraphicTaggingLazyRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/cuesheets/$cuesheetId': typeof DashboardCuesheetsCuesheetIdRoute
  '/dashboard/rundowns/$rundownId': typeof DashboardRundownsRundownIdRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/broadcast': typeof DashboardBroadcastIndexRoute
  '/dashboard/characters': typeof DashboardCharactersIndexRoute
  '/dashboard/cuesheets': typeof DashboardCuesheetsIndexRoute
  '/dashboard/datasources': typeof DashboardDatasourcesIndexRoute
  '/dashboard/rundowns': typeof DashboardRundownsIndexRoute
  '/dashboard/studio/bundles/$bundleId': typeof DashboardStudioBundlesBundleIdRoute
  '/dashboard/studio/graphics/$graphicId': typeof DashboardStudioGraphicsGraphicIdRoute
  '/dashboard/studio/whiteboards/$whiteboardId': typeof DashboardStudioWhiteboardsWhiteboardIdRoute
  '/dashboard/assets/fonts': typeof DashboardAssetsFontsIndexRoute
  '/dashboard/assets/images': typeof DashboardAssetsImagesIndexRoute
  '/dashboard/studio/bundles': typeof DashboardStudioBundlesIndexRoute
  '/dashboard/studio/graphics': typeof DashboardStudioGraphicsIndexRoute
  '/dashboard/studio/overlays': typeof DashboardStudioOverlaysIndexRoute
  '/dashboard/studio/grid-templates': typeof DashboardStudioGridTemplatesIndexLazyRoute
  '/dashboard/studio/whiteboards': typeof DashboardStudioWhiteboardsIndexLazyRoute
  '/dashboard/studio/graphics/grid-templates/$templateId': typeof DashboardStudioGraphicsGridTemplatesTemplateIdRoute
  '/dashboard/studio/graphics/grid-templates/new': typeof DashboardStudioGraphicsGridTemplatesNewRoute
  '/dashboard/studio/overlays/editor/$pluginId': typeof DashboardStudioOverlaysEditorPluginIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/controller': typeof ControllerRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/render': typeof RenderRoute
  '/controller/$sessionId': typeof ControllerSessionIdRoute
  '/dashboard/ai-cuesheet': typeof DashboardAiCuesheetLazyRoute
  '/dashboard/graphic-tagging': typeof DashboardGraphicTaggingLazyRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/cuesheets/$cuesheetId': typeof DashboardCuesheetsCuesheetIdRoute
  '/dashboard/rundowns/$rundownId': typeof DashboardRundownsRundownIdRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/broadcast/': typeof DashboardBroadcastIndexRoute
  '/dashboard/characters/': typeof DashboardCharactersIndexRoute
  '/dashboard/cuesheets/': typeof DashboardCuesheetsIndexRoute
  '/dashboard/datasources/': typeof DashboardDatasourcesIndexRoute
  '/dashboard/rundowns/': typeof DashboardRundownsIndexRoute
  '/dashboard/studio/bundles/$bundleId': typeof DashboardStudioBundlesBundleIdRoute
  '/dashboard/studio/graphics/$graphicId': typeof DashboardStudioGraphicsGraphicIdRoute
  '/dashboard/studio/whiteboards/$whiteboardId': typeof DashboardStudioWhiteboardsWhiteboardIdRoute
  '/dashboard/assets/fonts/': typeof DashboardAssetsFontsIndexRoute
  '/dashboard/assets/images/': typeof DashboardAssetsImagesIndexRoute
  '/dashboard/studio/bundles/': typeof DashboardStudioBundlesIndexRoute
  '/dashboard/studio/graphics/': typeof DashboardStudioGraphicsIndexRoute
  '/dashboard/studio/overlays/': typeof DashboardStudioOverlaysIndexRoute
  '/dashboard/studio/grid-templates/': typeof DashboardStudioGridTemplatesIndexLazyRoute
  '/dashboard/studio/whiteboards/': typeof DashboardStudioWhiteboardsIndexLazyRoute
  '/dashboard/studio/graphics/grid-templates/$templateId': typeof DashboardStudioGraphicsGridTemplatesTemplateIdRoute
  '/dashboard/studio/graphics/grid-templates/new': typeof DashboardStudioGraphicsGridTemplatesNewRoute
  '/dashboard/studio/overlays/editor/$pluginId': typeof DashboardStudioOverlaysEditorPluginIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/controller'
    | '/dashboard'
    | '/login'
    | '/render'
    | '/controller/$sessionId'
    | '/dashboard/ai-cuesheet'
    | '/dashboard/graphic-tagging'
    | '/dashboard/'
    | '/dashboard/cuesheets/$cuesheetId'
    | '/dashboard/rundowns/$rundownId'
    | '/dashboard/admin/'
    | '/dashboard/broadcast/'
    | '/dashboard/characters/'
    | '/dashboard/cuesheets/'
    | '/dashboard/datasources/'
    | '/dashboard/rundowns/'
    | '/dashboard/studio/bundles/$bundleId'
    | '/dashboard/studio/graphics/$graphicId'
    | '/dashboard/studio/whiteboards/$whiteboardId'
    | '/dashboard/assets/fonts/'
    | '/dashboard/assets/images/'
    | '/dashboard/studio/bundles/'
    | '/dashboard/studio/graphics/'
    | '/dashboard/studio/overlays/'
    | '/dashboard/studio/grid-templates/'
    | '/dashboard/studio/whiteboards/'
    | '/dashboard/studio/graphics/grid-templates/$templateId'
    | '/dashboard/studio/graphics/grid-templates/new'
    | '/dashboard/studio/overlays/editor/$pluginId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/controller'
    | '/login'
    | '/render'
    | '/controller/$sessionId'
    | '/dashboard/ai-cuesheet'
    | '/dashboard/graphic-tagging'
    | '/dashboard'
    | '/dashboard/cuesheets/$cuesheetId'
    | '/dashboard/rundowns/$rundownId'
    | '/dashboard/admin'
    | '/dashboard/broadcast'
    | '/dashboard/characters'
    | '/dashboard/cuesheets'
    | '/dashboard/datasources'
    | '/dashboard/rundowns'
    | '/dashboard/studio/bundles/$bundleId'
    | '/dashboard/studio/graphics/$graphicId'
    | '/dashboard/studio/whiteboards/$whiteboardId'
    | '/dashboard/assets/fonts'
    | '/dashboard/assets/images'
    | '/dashboard/studio/bundles'
    | '/dashboard/studio/graphics'
    | '/dashboard/studio/overlays'
    | '/dashboard/studio/grid-templates'
    | '/dashboard/studio/whiteboards'
    | '/dashboard/studio/graphics/grid-templates/$templateId'
    | '/dashboard/studio/graphics/grid-templates/new'
    | '/dashboard/studio/overlays/editor/$pluginId'
  id:
    | '__root__'
    | '/'
    | '/controller'
    | '/dashboard'
    | '/login'
    | '/render'
    | '/controller/$sessionId'
    | '/dashboard/ai-cuesheet'
    | '/dashboard/graphic-tagging'
    | '/dashboard/'
    | '/dashboard/cuesheets/$cuesheetId'
    | '/dashboard/rundowns/$rundownId'
    | '/dashboard/admin/'
    | '/dashboard/broadcast/'
    | '/dashboard/characters/'
    | '/dashboard/cuesheets/'
    | '/dashboard/datasources/'
    | '/dashboard/rundowns/'
    | '/dashboard/studio/bundles/$bundleId'
    | '/dashboard/studio/graphics/$graphicId'
    | '/dashboard/studio/whiteboards/$whiteboardId'
    | '/dashboard/assets/fonts/'
    | '/dashboard/assets/images/'
    | '/dashboard/studio/bundles/'
    | '/dashboard/studio/graphics/'
    | '/dashboard/studio/overlays/'
    | '/dashboard/studio/grid-templates/'
    | '/dashboard/studio/whiteboards/'
    | '/dashboard/studio/graphics/grid-templates/$templateId'
    | '/dashboard/studio/graphics/grid-templates/new'
    | '/dashboard/studio/overlays/editor/$pluginId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ControllerRoute: typeof ControllerRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  RenderRoute: typeof RenderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/render': {
      id: '/render'
      path: '/render'
      fullPath: '/render'
      preLoaderRoute: typeof RenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controller': {
      id: '/controller'
      path: '/controller'
      fullPath: '/controller'
      preLoaderRoute: typeof ControllerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/graphic-tagging': {
      id: '/dashboard/graphic-tagging'
      path: '/graphic-tagging'
      fullPath: '/dashboard/graphic-tagging'
      preLoaderRoute: typeof DashboardGraphicTaggingLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ai-cuesheet': {
      id: '/dashboard/ai-cuesheet'
      path: '/ai-cuesheet'
      fullPath: '/dashboard/ai-cuesheet'
      preLoaderRoute: typeof DashboardAiCuesheetLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/controller/$sessionId': {
      id: '/controller/$sessionId'
      path: '/$sessionId'
      fullPath: '/controller/$sessionId'
      preLoaderRoute: typeof ControllerSessionIdRouteImport
      parentRoute: typeof ControllerRoute
    }
    '/dashboard/rundowns/': {
      id: '/dashboard/rundowns/'
      path: '/rundowns'
      fullPath: '/dashboard/rundowns/'
      preLoaderRoute: typeof DashboardRundownsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/datasources/': {
      id: '/dashboard/datasources/'
      path: '/datasources'
      fullPath: '/dashboard/datasources/'
      preLoaderRoute: typeof DashboardDatasourcesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cuesheets/': {
      id: '/dashboard/cuesheets/'
      path: '/cuesheets'
      fullPath: '/dashboard/cuesheets/'
      preLoaderRoute: typeof DashboardCuesheetsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/characters/': {
      id: '/dashboard/characters/'
      path: '/characters'
      fullPath: '/dashboard/characters/'
      preLoaderRoute: typeof DashboardCharactersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/broadcast/': {
      id: '/dashboard/broadcast/'
      path: '/broadcast'
      fullPath: '/dashboard/broadcast/'
      preLoaderRoute: typeof DashboardBroadcastIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/admin'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/rundowns/$rundownId': {
      id: '/dashboard/rundowns/$rundownId'
      path: '/rundowns/$rundownId'
      fullPath: '/dashboard/rundowns/$rundownId'
      preLoaderRoute: typeof DashboardRundownsRundownIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cuesheets/$cuesheetId': {
      id: '/dashboard/cuesheets/$cuesheetId'
      path: '/cuesheets/$cuesheetId'
      fullPath: '/dashboard/cuesheets/$cuesheetId'
      preLoaderRoute: typeof DashboardCuesheetsCuesheetIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/studio/whiteboards/': {
      id: '/dashboard/studio/whiteboards/'
      path: '/studio/whiteboards'
      fullPath: '/dashboard/studio/whiteboards/'
      preLoaderRoute: typeof DashboardStudioWhiteboardsIndexLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/studio/grid-templates/': {
      id: '/dashboard/studio/grid-templates/'
      path: '/studio/grid-templates'
      fullPath: '/dashboard/studio/grid-templates/'
      preLoaderRoute: typeof DashboardStudioGridTemplatesIndexLazyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/studio/overlays/': {
      id: '/dashboard/studio/overlays/'
      path: '/studio/overlays'
      fullPath: '/dashboard/studio/overlays/'
      preLoaderRoute: typeof DashboardStudioOverlaysIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/studio/graphics/': {
      id: '/dashboard/studio/graphics/'
      path: '/studio/graphics'
      fullPath: '/dashboard/studio/graphics/'
      preLoaderRoute: typeof DashboardStudioGraphicsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/studio/bundles/': {
      id: '/dashboard/studio/bundles/'
      path: '/studio/bundles'
      fullPath: '/dashboard/studio/bundles/'
      preLoaderRoute: typeof DashboardStudioBundlesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/assets/images/': {
      id: '/dashboard/assets/images/'
      path: '/assets/images'
      fullPath: '/dashboard/assets/images/'
      preLoaderRoute: typeof DashboardAssetsImagesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/assets/fonts/': {
      id: '/dashboard/assets/fonts/'
      path: '/assets/fonts'
      fullPath: '/dashboard/assets/fonts/'
      preLoaderRoute: typeof DashboardAssetsFontsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/studio/whiteboards/$whiteboardId': {
      id: '/dashboard/studio/whiteboards/$whiteboardId'
      path: '/studio/whiteboards/$whiteboardId'
      fullPath: '/dashboard/studio/whiteboards/$whiteboardId'
      preLoaderRoute: typeof DashboardStudioWhiteboardsWhiteboardIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/studio/graphics/$graphicId': {
      id: '/dashboard/studio/graphics/$graphicId'
      path: '/studio/graphics/$graphicId'
      fullPath: '/dashboard/studio/graphics/$graphicId'
      preLoaderRoute: typeof DashboardStudioGraphicsGraphicIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/studio/bundles/$bundleId': {
      id: '/dashboard/studio/bundles/$bundleId'
      path: '/studio/bundles/$bundleId'
      fullPath: '/dashboard/studio/bundles/$bundleId'
      preLoaderRoute: typeof DashboardStudioBundlesBundleIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/studio/overlays/editor/$pluginId': {
      id: '/dashboard/studio/overlays/editor/$pluginId'
      path: '/studio/overlays/editor/$pluginId'
      fullPath: '/dashboard/studio/overlays/editor/$pluginId'
      preLoaderRoute: typeof DashboardStudioOverlaysEditorPluginIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/studio/graphics/grid-templates/new': {
      id: '/dashboard/studio/graphics/grid-templates/new'
      path: '/studio/graphics/grid-templates/new'
      fullPath: '/dashboard/studio/graphics/grid-templates/new'
      preLoaderRoute: typeof DashboardStudioGraphicsGridTemplatesNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/studio/graphics/grid-templates/$templateId': {
      id: '/dashboard/studio/graphics/grid-templates/$templateId'
      path: '/studio/graphics/grid-templates/$templateId'
      fullPath: '/dashboard/studio/graphics/grid-templates/$templateId'
      preLoaderRoute: typeof DashboardStudioGraphicsGridTemplatesTemplateIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface ControllerRouteChildren {
  ControllerSessionIdRoute: typeof ControllerSessionIdRoute
}

const ControllerRouteChildren: ControllerRouteChildren = {
  ControllerSessionIdRoute: ControllerSessionIdRoute,
}

const ControllerRouteWithChildren = ControllerRoute._addFileChildren(
  ControllerRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAiCuesheetLazyRoute: typeof DashboardAiCuesheetLazyRoute
  DashboardGraphicTaggingLazyRoute: typeof DashboardGraphicTaggingLazyRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCuesheetsCuesheetIdRoute: typeof DashboardCuesheetsCuesheetIdRoute
  DashboardRundownsRundownIdRoute: typeof DashboardRundownsRundownIdRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
  DashboardBroadcastIndexRoute: typeof DashboardBroadcastIndexRoute
  DashboardCharactersIndexRoute: typeof DashboardCharactersIndexRoute
  DashboardCuesheetsIndexRoute: typeof DashboardCuesheetsIndexRoute
  DashboardDatasourcesIndexRoute: typeof DashboardDatasourcesIndexRoute
  DashboardRundownsIndexRoute: typeof DashboardRundownsIndexRoute
  DashboardStudioBundlesBundleIdRoute: typeof DashboardStudioBundlesBundleIdRoute
  DashboardStudioGraphicsGraphicIdRoute: typeof DashboardStudioGraphicsGraphicIdRoute
  DashboardStudioWhiteboardsWhiteboardIdRoute: typeof DashboardStudioWhiteboardsWhiteboardIdRoute
  DashboardAssetsFontsIndexRoute: typeof DashboardAssetsFontsIndexRoute
  DashboardAssetsImagesIndexRoute: typeof DashboardAssetsImagesIndexRoute
  DashboardStudioBundlesIndexRoute: typeof DashboardStudioBundlesIndexRoute
  DashboardStudioGraphicsIndexRoute: typeof DashboardStudioGraphicsIndexRoute
  DashboardStudioOverlaysIndexRoute: typeof DashboardStudioOverlaysIndexRoute
  DashboardStudioGridTemplatesIndexLazyRoute: typeof DashboardStudioGridTemplatesIndexLazyRoute
  DashboardStudioWhiteboardsIndexLazyRoute: typeof DashboardStudioWhiteboardsIndexLazyRoute
  DashboardStudioGraphicsGridTemplatesTemplateIdRoute: typeof DashboardStudioGraphicsGridTemplatesTemplateIdRoute
  DashboardStudioGraphicsGridTemplatesNewRoute: typeof DashboardStudioGraphicsGridTemplatesNewRoute
  DashboardStudioOverlaysEditorPluginIdRoute: typeof DashboardStudioOverlaysEditorPluginIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAiCuesheetLazyRoute: DashboardAiCuesheetLazyRoute,
  DashboardGraphicTaggingLazyRoute: DashboardGraphicTaggingLazyRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCuesheetsCuesheetIdRoute: DashboardCuesheetsCuesheetIdRoute,
  DashboardRundownsRundownIdRoute: DashboardRundownsRundownIdRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
  DashboardBroadcastIndexRoute: DashboardBroadcastIndexRoute,
  DashboardCharactersIndexRoute: DashboardCharactersIndexRoute,
  DashboardCuesheetsIndexRoute: DashboardCuesheetsIndexRoute,
  DashboardDatasourcesIndexRoute: DashboardDatasourcesIndexRoute,
  DashboardRundownsIndexRoute: DashboardRundownsIndexRoute,
  DashboardStudioBundlesBundleIdRoute: DashboardStudioBundlesBundleIdRoute,
  DashboardStudioGraphicsGraphicIdRoute: DashboardStudioGraphicsGraphicIdRoute,
  DashboardStudioWhiteboardsWhiteboardIdRoute:
    DashboardStudioWhiteboardsWhiteboardIdRoute,
  DashboardAssetsFontsIndexRoute: DashboardAssetsFontsIndexRoute,
  DashboardAssetsImagesIndexRoute: DashboardAssetsImagesIndexRoute,
  DashboardStudioBundlesIndexRoute: DashboardStudioBundlesIndexRoute,
  DashboardStudioGraphicsIndexRoute: DashboardStudioGraphicsIndexRoute,
  DashboardStudioOverlaysIndexRoute: DashboardStudioOverlaysIndexRoute,
  DashboardStudioGridTemplatesIndexLazyRoute:
    DashboardStudioGridTemplatesIndexLazyRoute,
  DashboardStudioWhiteboardsIndexLazyRoute:
    DashboardStudioWhiteboardsIndexLazyRoute,
  DashboardStudioGraphicsGridTemplatesTemplateIdRoute:
    DashboardStudioGraphicsGridTemplatesTemplateIdRoute,
  DashboardStudioGraphicsGridTemplatesNewRoute:
    DashboardStudioGraphicsGridTemplatesNewRoute,
  DashboardStudioOverlaysEditorPluginIdRoute:
    DashboardStudioOverlaysEditorPluginIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ControllerRoute: ControllerRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  RenderRoute: RenderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
